---
name: ğŸ” Sync Upstream Repo

on:
  schedule:
    - cron: '0 * * * *'  # æ¯å°æ—¶æ‰§è¡Œä¸€æ¬¡
  #workflow_dispatch: true  # å…è®¸æ‰‹åŠ¨ç‚¹å‡»åŒæ­¥

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # é˜²æ­¢ git push å‡ºé”™
          fetch-depth: 0  # æ‹‰å–å®Œæ•´æäº¤å†å²

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/brenner-tobias/ha-addons.git
          git fetch upstream
          git merge upstream/main --allow-unrelated-histories || echo "Nothing to merge"
          git push origin main
